# This file was generated by GoReleaser. DO NOT EDIT.
class Tv < Formula
  desc "tv is a tool to view the delimited file in terminal."
  homepage "https://github.com/codechenx/tv"
  version "0.5.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/codechenx/tv/releases/download/v0.5.2/tv_0.5.2_darwin_amd64.tar.gz"
    sha256 "97b2a8d720c69d54e04c0c1988627609ff1dd1aa4e828412bc141ee3d0faf9ac"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/codechenx/tv/releases/download/v0.5.2/tv_0.5.2_linux_amd64.tar.gz"
      sha256 "3ff5cd51c7e1324067f1116ef64fb87b5188aa66a54ac82c2714ca1bba279166"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/codechenx/tv/releases/download/v0.5.2/tv_0.5.2_linux_arm64.tar.gz"
        sha256 "b09a6a3a5d00d716edae7182ac9c8782f02a1fd91b675675580266cdf2081165"
      else
      end
    end
  end

  def install
    bin.install "tv"
  end
end
