# This file was generated by GoReleaser. DO NOT EDIT.
class Tv < Formula
  desc "tv is a tool to view the delimited file in terminal."
  homepage "https://github.com/codechenx/tv"
  version "0.5.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/codechenx/tv/releases/download/v0.5.2/tv_0.5.2_darwin_amd64.tar.gz"
    sha256 "eeb6aa44fcdfa29eb1427266e69676d850b0604a16bd4e9f792675f36889bdf7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/codechenx/tv/releases/download/v0.5.2/tv_0.5.2_linux_amd64.tar.gz"
      sha256 "b117e889629f5ad4668e5291d0288b0ce31c553b76841196869e4bcb6bf63890"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/codechenx/tv/releases/download/v0.5.2/tv_0.5.2_linux_arm64.tar.gz"
        sha256 "e6f19463a82635d077e256d7486eea30e8e61b86dac0ff65b69b232afb270db6"
      else
      end
    end
  end

  def install
    bin.install "tv"
  end
end
